### ISSUE TITLE
Permissions not correct

### ISSUE THREAD

**Issue by sphr2k** [Mesa/oxid#1]
Hi,

could you check the permissions for Oxid? Initially, Server configuration > Files/folders access rights shows a red cross; after fixing permissions according to 

https://www.oxid-esales.com/de/support-services/dokumentation-und-hilfe/oxid-eshop/installation/oxid-eshop-neu-installieren/installation-pruefen.html

it works.

Thanks,
Jan

**Comment by DAN-XO** [comment]
Hi Jan,

I'll check the file permissions at the Weekend at home.

Oxid should be installed and you wouldn't see the instaltion page.
Did you clone this repo or do you have a problem with the docker/oxid image?

This repo is the source repo for https://hub.docker.com/r/mesa/oxid/ . You can use the resulting image in your project docker-compose.yml.

Look at https://github.com/Mesa/oxid/tree/master/demo for an example how to use this image.

If I made the wrong assumptions, help me out with more information.

**Comment by sphr2k** [comment]
HI Mesa,

I used docker-compose to run mesa/oxid from Docker Hub - I'm not a docker expert, but to me it seems like something has changed (in the current version of Oxid?) that has not yet been factored in.

Thanks for your help,
Jan

**Comment by DAN-XO** [comment]
Hi Jan,

i finally found my mistake. I didn't remove the setup folder while building the image and updated the README to clarify the inital/first project setup.

You need all files from the /demo folder and you are ready to go. Just execute docker-compose up and visit http://localhost.

Plus i updated to oxid 4.10.1

Let me know if you need some additional help anyway.
