### ISSUE TITLE
Image upload on articles/products seems to be broken

### ISSUE THREAD

**Issue by pebra** [Mesa/oxid#2]
I was trying out your image and was not able to upload any pictures for articles via the admin interface
![upload_screen](https://cloud.githubusercontent.com/assets/820917/23103979/10ac0634-f6c5-11e6-9108-13a6403083ce.png)

This happens with the stock configuration from the demo folder, as well as with my own attempt.
Did you experience the same issue?

**Comment by DAN-XO** [comment]
Thanks for reporting.

No I wasn't aware of this issue. This is maybe a read/write problem i missed. I have to investigate further this evening.

**Comment by DAN-XO** [comment]
Hi @pebra,

I updated the correspnding docker-compose.yml.

I added the following line:
`            OXID_COMPILE_DIR: "/data/tmp"`
to change oxid compile dir. This should resolve your issue.

**Comment by pebra** [comment]
This did the trick, awesome, thank you =)
