### ISSUE TITLE
Incorrect tagging

### ISSUE THREAD

**Issue by uuf6429** [Mesa/oxid#4]
Tagging is very confusing and doesn't seem to follow best practices.

Firstly, let's look at `php5.6` and `php7` tags... the image is about OXID, not PHP. PHP is the secondary concern.

The main concern is: What's the OXID version?
If that answer is "latest" then it goes against the point of having a "latest" tag.

Secondly, I don't see the need for a db image... especially since people might want to use a different db system, but it's not a big problem for me.

Finally, it's entirely reasonable to need to test something against different OXID versions, so you should probably ship different tags for different (major) OXID versions.

For inspiration, I'd urge you to give the WordPress repository a look.

**Comment by DAN-XO** [comment]
You are right, tagging is messed up. All your questions are answered in the README.md.

This images are optimized for oxid and nothing more (OXID is not preinstalled). How will you test the latest OXID Version against PHP 7.2, 7.1, 5.6? So I decided to create the container configured for OXID with one specific PHP Version and an Installer/helper to download the OXID Version of your choice.

So you have the free choice to use one, two or all container for you development setup and you can test your OXID Version X:XX with PHP 5.6 AND PHP7 at the same time.

The Database container was added for simplicity and to prevent the nasty UTF-8 Error messages at setup (default charset utf-8, but you will get it when you messed up your container), and hey suprise you can change YOUR docker-compose.yaml and use a different Database, this is the best part of Docker:

I'am creating small pieces and you can stick them together the way you want or need to create your Development Setup.

For inspiration, I dont give a fuck what the WordPress repository a looks like.

**Comment by uuf6429** [comment]
Well, that's the problem, you claim that you provide the pieces when in fact you provide three big images that are entirely unusable, even for development.

An environment suitable for development requires a certain level of customisation, unless your target audience is some random freelancer.

As to the database thing, you're perfectly right! You can do all of that in your `docker-compose.yml`.... so why a whole image? It gives an impression that there is something special about it.

As to the official [WordPress docker repo](https://hub.docker.com/_/wordpress/); it looks like a dozen other docker repos that are easy to work with and follow some best practices.

----

Sure, feel free to ignore any and all advise, your repo will be ignored just like the other (much worse) oxid repos that I've seen already, shame in my opinion.

**Comment by DAN-XO** [comment]
You claim that something is broken, and the only things you provide are advices.

Stop wasting my time and please start your own repo, 
or the best solution would be, you spend your spare time, optimze the container and provide a pull request for the sake of all OXID developer.

I'am awaiting your pull-request.

**Comment by uuf6429** [comment]
I'd love to contribute, really. And I might eventually have to write my own, since (as I said) the ones out there are quite inadequate, however:
1. I don't think that with that attitude I'd get to see the PR to your repo getting merged
2. I'm currently fixing and taking care of many other projects - none of which were as disrespectful as this one
3. As I mentioned several times already, there are a tonne of repositories that one get inspiration from... where inspiration basically means cloning the repository, replacing a few keywords, moving over your scripts and start a build
4. I've spent enough time trying to get this to work, I don't want to risk wasting more time discussing how it should work
5. It's hardly fair to get free work done just because you can't handle someone else's opinion/advise

There's numerous ways of replying to such a thing... anything between "I don't have the time" to "I'll give it a thought". Your reply was basically a "f*ck off, I know better". That attitude really won't earn you any freebies.

**Comment by DAN-XO** [comment]
1.) My point with the pull request was serious, I am total capable to argue and accept a pull request from the same person.
2.) Me too..
3.) When you dont't like me, go and help the other to become the "Unicorn - Rockstart Programmer" you are and dont waste my time.
4.) Just ask for help and tell me what you tried and I will help. Stop giving advise, when you are asking for help. You didnt describe your problem until now.
5.) Why should I handle your advice? Respect is something you earn, its not a gift.

There are numerous ways of asking for help, you choose the wrong. You are complaining about software, others created in they spare timed (for fun) without earning one cent and all you contribute are unnecessary advices.

Still awaiting your PR... or some desciption of what went wrong, including some error messages to improve this repo.

**Comment by uuf6429** [comment]
> There are numerous ways of asking for help, you choose the wrong. You are complaining about software, others created in they spare timed (for fun) without earning one cent and all you contribute are unnecessary advices.

Daniel, I've provided *constructive criticism* from point one. If you read anything past the title, I explained why naming your tags "phpXX" for a non-PHP image is a bad idea. I'm not going to explain this anther time.

I agree, respect is to be earned, but from the first comment you showed nothing but vulgar disrespect to a simple post which you could have shrugged off in many ways without resorting to insults.

If you don't know how to handle advice - which you definitely do not, when you keep saying "put your advise up your arse" - then you're not fit for this game.

At this point you should realise that you won't get any help with your precious repo, not by me and probably not by anyone else.
